spring:
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: analytics-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "group.instance.id": "1"
        "spring.json.trusted.packages": "*"
  cassandra:
    contact-points: localhost
    keyspace-name: products
    port: 9042
    schema-action: create_if_not_exists
    local-datacenter: datacenter1
    entity-base-package: com.nl
server:
  port: 8082